---
- name: Install
  become: yes
  apt: name=nginx state=latest

- name: start
  become: yes
  service: name=nginx state=started enabled=yes

- name: Supprimer default.conf
  become: yes
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: reload

- name: PHP
  include: php.yml  

- name: Configuration du site
  include: site.yml
  with_items: domain  
...
