---
- name: APT update
  apt: update_cache=yes

- name: Install php
  apt : name={{ item }} state=latest
  with_items: 
        - php7.0
        - php7.0-common
        - php7.0-cli
        - php7.0-intl
        - php7.0-curl
        - php7.0-cgi
        - php7.0-fpm
        - php7.0-mcrypt
        - php7.0-mysql
        - php7.0-gd


- name: Retrait des fonctions dangeureuses
  lineinfile: dest=/etc/php/7.0/fpm/php.ini regexp='disable_functions[\s]?=' line='disable_functions = exec, passthru,shell_exec,proc_open,popen'

- lineinfile: dest=/etc/php/7.0/fpm/php.ini regexp='post_max_size[\s]?=' line='post_max_size = {{ php_post_max_size }}'
- lineinfile: dest=/etc/php/7.0/fpm/php.ini regexp='upload_max_filesize[\s]?=' line='upload_max_filesize = {{ php_upload_max_filesize }}'
- lineinfile: dest=/etc/php/7.0/fpm/php.ini regexp='memory_limit[\s]?=' line='memory_limit = {{ php_memory_limit }}'
- lineinfile: dest=/etc/php/7.0/fpm/php.ini regexp='date.timezone[\s]?=' line='date.timezone = {{ php_timezone }}'
  notify: php restart  
...
