---
- name: Creation du dossier
  become: yes
  file: path=/home/{{ user }}/{{ domain }} state=directory owner={{ user }}

- name: Lien vers WWW
  become: yes
  file: src=/home/{{ user }}/{{ domain }} dest=/var/www/{{ domain }} force=yes state=link

- name: Creation de la configuration nginx
  template: src=templates/nginx.j2 dest=/etc/nginx/sites-available/{{ domain }} force=yes
  notify: reload

- name: Activation du domaine {{ domain }}
  file: src=/etc/nginx/sites-available/{{ domain }} dest=/etc/nginx/sites-enabled/{{ domain }} state=link
  notify: reload
...
